const classes = [
  {
    "name": "Apple scab",
    "article": "Apple scab adalah penyakit jamur yang umumnya menyerang pohon apel. Penyakit ini disebabkan oleh patogen Venturia inaequalis. Penyakit ini terutama mempengaruhi daun, buah, dan dalam beberapa kasus, ranting pohon apel. Apple scab muncul sebagai lesi berwarna gelap dan bersisik pada daun, menyebabkan daun menggulung dan akhirnya gugur lebih awal. Buah yang terinfeksi mengembangkan bercak kasar yang mirip dengan luka, membuatnya tidak menarik dan mengurangi nilai jualnya. Penyakit ini dapat melemahkan pohon, mempengaruhi kesehatan dan produktivitas secara keseluruhan. Apple scab menyebar melalui spora yang dilepaskan selama cuaca hujan atau lembab, memfasilitasi perpindahannya dari tanaman yang terinfeksi ke tanaman yang sehat. Praktik pengelolaan yang tepat seperti memilih varietas apel yang tahan, menjaga jarak yang cukup antara pohon, memastikan sirkulasi udara yang baik, menjaga kebersihan yang tepat, dan menerapkan penggunaan fungisida tepat waktu dapat membantu mencegah dan mengendalikan apple scab. Deteksi dini dan tindakan proaktif sangat penting dalam mengurangi dampak penyakit ini dan menjaga kesehatan serta vitalitas kebun apel."
  },
  {
    "name": "Apple Black rot",
    "article": "Apple Black rot adalah penyakit yang disebabkan oleh jamur Botryosphaeria obtusa. Penyakit ini umumnya menyerang buah apel dan bisa menyebabkan kerusakan serius pada panen. Apple Black rot menyebabkan buah apel mengalami busuk basah yang berkembang menjadi lesi berwarna coklat atau hitam. Lesi ini bisa membesar dan menyebar ke seluruh permukaan buah, membuatnya rusak dan tidak layak konsumsi. Selain itu, penyakit ini juga dapat menyerang daun, ranting, dan batang apel. Faktor lingkungan seperti kelembaban tinggi dan curah hujan yang berkepanjangan memfasilitasi penyebaran penyakit ini. Untuk mencegah Apple Black rot, penting untuk menjaga kebersihan kebun apel, membuang buah-buah yang terinfeksi, dan memangkas bagian tanaman yang terkena penyakit. Penggunaan fungisida yang direkomendasikan juga dapat membantu dalam pengendalian penyakit ini. Pemantauan rutin dan tindakan pengendalian yang cepat sangat penting dalam menjaga kesehatan pohon apel dan mengurangi dampak Apple Black rot pada produksi buah."
  },
  {
    "name": "Apple Cedar apple rust",
    "article": "Apple Cedar apple rust adalah penyakit yang disebabkan oleh jamur Gymnosporangium juniperi-virginianae. Penyakit ini melibatkan dua inang, yaitu pohon apel dan pohon cedar (misalnya, juniper atau red cedar). Pada tanaman apel, Cedar apple rust menyebabkan pembentukan lesi berwarna oranye atau kuning pada daun, buah, dan ranting. Lesi tersebut kemudian berkembang menjadi bintik-bintik hitam yang berkerut. Penyakit ini dapat merusak tanaman apel, mengurangi kualitas buah, dan bahkan menyebabkan kerugian ekonomi. Penularan penyakit terjadi ketika spora jamur dipindahkan oleh angin dari pohon cedar ke pohon apel. Untuk mengendalikan Cedar apple rust, praktik pengelolaan meliputi penghapusan pohon cedar terdekat, sanitasi kebun dengan membuang daun-daun yang terinfeksi, dan penggunaan fungisida yang direkomendasikan oleh ahli pertanian. Penting untuk melakukan tindakan pencegahan sejak dini dan memantau kondisi kebun apel secara teratur untuk mengurangi risiko infeksi dan menjaga kesehatan pohon apel."
  },
  {
    "name": "Apple healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Bean angular leaf spot",
    "article": "Bean angular leaf spot, juga dikenal sebagai bercak daun sudut pada kacang, adalah penyakit umum yang menyerang tanaman kacang. Penyakit ini disebabkan oleh bakteri Pseudomonas syringae pv. phaseolicola. Bercak daun sudut pada kacang muncul sebagai lesi kecil yang tergenang air pada daun, yang secara bertahap membesar dan membentuk sudut dengan lingkaran kuning di sekitarnya. Seiring perkembangan penyakit, bercak-barcak tersebut dapat berubah menjadi cokelat atau hitam, menyebabkan gugur daun dan mempengaruhi kesehatan keseluruhan tanaman. Penyakit bercak daun sudut pada kacang umumnya menyebar melalui percikan air hujan, air irigasi, atau serasah tanaman yang terinfeksi. Untuk mengendalikan dan mencegah penyakit ini, beberapa langkah dapat diambil. Menanam varietas kacang yang tahan terhadap penyakit ini merupakan strategi yang efektif. Selain itu, melakukan rotasi tanaman, memberikan jarak yang cukup antara tanaman, dan menjaga sirkulasi udara yang baik dapat membantu meminimalkan penyebaran penyakit. Teknik irigasi yang tepat, seperti menghindari penyiraman dari atas, juga dapat mengurangi risiko infeksi. Jika bercak daun sudut pada kacang terdeteksi, segera hilangkan dan hancurkan bagian tanaman yang terinfeksi untuk mencegah penyebaran lebih lanjut. Terakhir, penggunaan penyemprotan tembaga atau antibiotik dapat dipertimbangkan sebagai tindakan pencegahan atau penyembuhan, dengan mengikuti petunjuk yang direkomendasikan. Memantau secara teratur tanaman untuk gejala dan menerapkan praktik pengelolaan yang tepat sangat penting dalam mengendalikan bercak daun sudut pada kacang dan menjaga kesehatan serta produktivitas tanaman kacang."
  },
  {
    "name": "Bean healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Bean rust",
    "article": "Bean rust, atau karat kacang, adalah penyakit yang umum menyerang tanaman kacang. Penyakit ini disebabkan oleh jamur Uromyces appendiculatus. Karat kacang ditandai dengan munculnya bercak kuning atau oranye pada daun, batang, dan polong kacang. Seiring perkembangan penyakit, bercak-bercak tersebut berkembang menjadi pustula-pustula berwarna cokelat kehitaman yang berisi spora jamur. Serangan karat kacang dapat menyebabkan penurunan hasil panen dan mengganggu pertumbuhan tanaman. Penyakit ini biasanya menyebar melalui spora jamur yang terbawa oleh angin, hujan, atau kontak langsung antara tanaman yang terinfeksi dan sehat. Untuk mengendalikan karat kacang, langkah-langkah pencegahan dan pengelolaan perlu dilakukan. Memilih varietas kacang yang tahan terhadap karat merupakan langkah penting. Menjaga kebersihan kebun dengan membuang sisa-sisa tanaman yang terinfeksi, menjaga jarak antar tanaman, dan mempromosikan sirkulasi udara yang baik dapat membantu mengurangi penyebaran penyakit. Penggunaan fungisida yang direkomendasikan juga bisa dipertimbangkan untuk mengendalikan serangan karat yang parah. Pemantauan rutin tanaman untuk mendeteksi gejala awal karat dan tindakan pengendalian yang cepat adalah kunci dalam menjaga keberhasilan pertanaman kacang dan mencegah penyebaran karat kacang."
  },
  {
    "name": "Blueberry healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Cherry (including sour) Powdery mildew",
    "article": "Cherry powdery mildew, atau karat tepung pada ceri (termasuk ceri asam), adalah penyakit yang disebabkan oleh jamur Podosphaera clandestina. Karat tepung pada ceri ditandai dengan adanya lapisan serbuk putih yang menutupi daun, ranting, dan buah ceri. Serbuk putih tersebut terutama muncul pada permukaan atas daun dan bagian yang masih muda. Infeksi yang parah dapat menyebabkan daun keriput, menggulung, dan gugur lebih awal. Buah ceri yang terinfeksi juga dapat mengalami deformasi dan berkurang kualitasnya. Penyebaran karat tepung terjadi melalui spora jamur yang tersebar oleh angin atau kontak langsung dengan tanaman yang terinfeksi. Untuk mengendalikan karat tepung pada ceri, langkah-langkah pengelolaan perlu dilakukan. Hal ini meliputi memilih varietas ceri yang toleran terhadap penyakit, menjaga kebersihan kebun dengan membuang sisa-sisa tanaman yang terinfeksi, memperhatikan sirkulasi udara yang baik, dan menjaga kelembaban yang rendah di lingkungan tumbuh. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan teratur terhadap tanaman ceri untuk mendeteksi gejala karat tepung sejak dini dan mengambil tindakan pengendalian yang tepat sangat penting untuk menjaga kesehatan tanaman ceri dan meminimalkan kerugian hasil panen."
  },
  {
    "name": "Cherry (including sour) healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Corn (maize) Cercospora leaf spot Gray leaf spot",
    "article": "Corn Cercospora leaf spot, atau bercak daun Cercospora pada jagung (maize), juga dikenal sebagai Gray leaf spot, adalah penyakit yang umum menyerang tanaman jagung. Penyakit ini disebabkan oleh jamur Cercospora zeae-maydis. Bercak daun Cercospora pada jagung ditandai dengan munculnya bercak-bercak berbentuk oval atau lonjong berwarna cokelat keabu-abuan pada daun, tangkai daun, dan malai jagung. Bercak tersebut dapat membesar dan bergabung menjadi lesi yang lebih besar. Serangan penyakit ini dapat mengurangi pertumbuhan dan produktivitas tanaman jagung, serta menyebabkan kehilangan hasil yang signifikan. Penyebaran penyakit terjadi melalui spora jamur yang tersebar oleh angin atau cairan, seperti tetesan hujan atau embun. Untuk mengendalikan bercak daun Cercospora pada jagung, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk pemilihan varietas jagung yang tahan terhadap penyakit, pemupukan yang seimbang, pengaturan irigasi yang baik, dan pengelolaan gulma yang efektif untuk mengurangi kelembaban dan meningkatkan sirkulasi udara di antara tanaman. Pemantauan rutin tanaman untuk mendeteksi gejala awal bercak daun Cercospora dan penerapan fungisida yang direkomendasikan dapat membantu mengendalikan penyakit ini. Tindakan pencegahan sejak dini, termasuk sanitasi kebun dan pengelolaan sisa tanaman yang terinfeksi, juga penting untuk mengurangi penyebaran bercak daun Cercospora dan menjaga kesehatan tanaman jagung."
  },
  {
    "name": "Corn (maize) Common rust",
    "article": "Karat umum pada jagung, atau corn common rust, adalah penyakit yang sering menyerang tanaman jagung. Penyakit ini disebabkan oleh jamur Puccinia sorghi. Karat umum pada jagung ditandai dengan munculnya bercak-bercak berwarna oranye atau kuning kecokelatan pada daun, tangkai daun, dan batang tanaman. Bercak tersebut kemudian berkembang menjadi pustula-pustula berwarna oranye yang mengandung spora jamur. Serangan penyakit ini dapat mempengaruhi pertumbuhan dan perkembangan tanaman jagung, mengurangi hasil panen, dan mengganggu kualitas tongkol jagung. Penyebaran karat umum terjadi melalui spora jamur yang dibawa oleh angin. Untuk mengendalikan karat umum pada jagung, langkah-langkah pengelolaan diperlukan. Ini meliputi pemilihan varietas jagung yang tahan terhadap karat, menjaga kebersihan kebun dengan menghilangkan gulma dan sisa-sisa tanaman yang terinfeksi, serta menjaga kelembaban rendah dan sirkulasi udara yang baik di antara tanaman. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman untuk mendeteksi gejala awal karat umum dan pengambilan tindakan pengendalian yang tepat merupakan langkah penting dalam menjaga kesehatan tanaman jagung dan meningkatkan hasil panen."
  },
  {
    "name": "Corn (maize) Northern Leaf Blight",
    "article": "Bercak Daun Utara pada jagung, atau corn northern leaf blight, adalah penyakit yang sering menyerang tanaman jagung. Penyakit ini disebabkan oleh jamur Exserohilum turcicum. Bercak Daun Utara pada jagung ditandai dengan munculnya bercak-bercak panjang berwarna cokelat pada daun-daun tanaman. Bercak tersebut dapat meluas dan menggabung menjadi lesi yang lebih besar, menyebabkan daun-daun terinfeksi menguning, mengering, dan akhirnya gugur. Serangan penyakit ini dapat mengurangi hasil panen jagung dan mengganggu kualitas tongkol jagung. Penyebaran Bercak Daun Utara terjadi melalui spora jamur yang tersebar oleh angin atau percikan air hujan. Untuk mengendalikan Bercak Daun Utara pada jagung, langkah-langkah pengelolaan diperlukan. Ini termasuk pemilihan varietas jagung yang tahan terhadap penyakit ini, rotasi tanaman, menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, dan menerapkan praktik sanitasi yang baik. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman untuk mendeteksi gejala awal Bercak Daun Utara dan pengambilan tindakan pengendalian yang tepat merupakan langkah penting dalam menjaga kesehatan tanaman jagung dan memaksimalkan hasil panen."
  },
  {
    "name": "Corn (maize) healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Grape Black rot",
    "article": "Black rot pada anggur adalah penyakit yang umum menyerang tanaman anggur. Penyakit ini disebabkan oleh jamur Guignardia bidwellii. Black rot pada anggur ditandai dengan munculnya bercak-bercak cokelat kehitaman pada daun, buah, dan ranting tanaman. Bercak tersebut berkembang menjadi lesi berbentuk bulat atau oval yang membusuk, dengan pinggiran berwarna hitam dan tengah berwarna cokelat yang terlihat kering dan bersisik. Serangan penyakit ini dapat mengakibatkan kerontokan daun, pembusukan buah, dan penurunan hasil panen yang signifikan. Penyebaran black rot terjadi melalui spora jamur yang tersebar oleh air hujan atau angin. Untuk mengendalikan black rot pada anggur, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk pemilihan varietas anggur yang tahan terhadap penyakit, pemangkasan yang tepat untuk meningkatkan sirkulasi udara, penyiraman yang bijaksana untuk menghindari kelembaban berlebih, dan pembersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman anggur untuk mendeteksi gejala awal black rot dan tindakan pengendalian yang cepat adalah kunci dalam menjaga kesehatan tanaman anggur dan meningkatkan hasil panen yang berkualitas."
  },
  {
    "name": "Grape Esca (Black Measles)",
    "article": "Grape Esca, juga dikenal sebagai Black Measles, adalah penyakit yang umum menyerang tanaman anggur. Penyakit ini disebabkan oleh kompleks mikroorganisme yang terdiri dari jamur dan bakteri. Esca pada anggur ditandai dengan munculnya gejala seperti daun-daun yang menguning, mengering, dan gugur secara prematur. Terdapat pula bercak-bercak hitam pada batang dan duri anggur yang tampak seperti tanda penyakit. Selain itu, penyakit ini dapat mengakibatkan pembusukan pada buah dan ranting tanaman. Serangan esca dapat menyebabkan penurunan kualitas buah dan produktivitas tanaman anggur yang signifikan. Penyebaran penyakit ini dapat terjadi melalui tanah, alat-alat pertanian yang terkontaminasi, dan spora yang dibawa oleh angin. Untuk mengendalikan esca pada anggur, langkah-langkah pengelolaan perlu dilakukan. Ini meliputi pemilihan varietas anggur yang tahan terhadap penyakit, pemangkasan yang tepat untuk meningkatkan sirkulasi udara, penerapan sanitasi yang baik, dan penggunaan agen biokontrol yang dapat membantu menghambat pertumbuhan patogen penyebab esca. Pemantauan rutin terhadap tanaman anggur untuk mendeteksi gejala awal esca dan penerapan tindakan pengendalian yang tepat sangat penting untuk menjaga kesehatan tanaman anggur dan meminimalkan kerugian hasil panen."
  },
  {
    "name": "Grape Leaf blight (Isariopsis Leaf Spot)",
    "article": "Grape Leaf Blight, juga dikenal sebagai Isariopsis Leaf Spot, adalah penyakit umum pada tanaman anggur. Penyakit ini disebabkan oleh jamur Isariopsis spp. Gejalanya meliputi bercak-bercak cokelat pada daun anggur. Bercak ini dapat membesar dan menyebabkan daun mengering dan gugur. Leaf Blight dapat mempengaruhi pertumbuhan dan produktivitas tanaman anggur serta mengurangi kualitas buah. Penyebaran penyakit ini terjadi melalui spora jamur yang menyebar melalui air dan angin. Pengendalian dapat dilakukan dengan memilih varietas yang tahan, memastikan sirkulasi udara yang baik, dan menjaga kebersihan kebun. Pemantauan rutin dan tindakan pengendalian yang tepat penting dalam menjaga kesehatan tanaman anggur dan hasil panen yang maksimal."
  },
  {
    "name": "Grape healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Orange Haunglongbing (Citrus greening)",
    "article": "Orange Huanglongbing, juga dikenal sebagai Citrus Greening, adalah penyakit serius yang menyerang tanaman jeruk. Penyakit ini disebabkan oleh bakteri Candidatus Liberibacter spp. Gejala utama Citrus Greening meliputi daun-daun yang kuning dan kerdil, pembusukan buah yang tidak matang, dan deformasi ranting. Penyakit ini dapat merusak pertumbuhan dan perkembangan tanaman jeruk, menyebabkan penurunan hasil panen yang signifikan, dan bahkan dapat membunuh pohon jeruk secara perlahan. Penyebaran penyakit ini terjadi melalui serangga vektor seperti kutu loncat jeruk. Mengendalikan Citrus Greening merupakan tantangan besar karena belum ada pengobatan yang efektif. Langkah-langkah pengelolaan yang dapat diambil termasuk memilih bibit yang bebas penyakit, melakukan pemantauan teratur, mengendalikan serangga vektor, dan menghilangkan pohon yang terinfeksi untuk mencegah penyebaran lebih lanjut. Kesadaran dan kerjasama antara petani, otoritas pertanian, dan peneliti sangat penting untuk melindungi industri jeruk dan menjaga keberlanjutan produksi jeruk yang sehat."
  },
  {
    "name": "Peach Bacterial spot",
    "article": "Bacterial spot pada persik adalah penyakit yang disebabkan oleh bakteri Xanthomonas arboricola pv. pruni. Penyakit ini ditandai dengan munculnya bercak-bercak merah atau cokelat pada daun, buah, dan ranting tanaman persik. Bercak tersebut dapat berkembang menjadi lepuhan berair pada buah yang terinfeksi. Serangan penyakit ini dapat menyebabkan kerusakan pada daun, pengguguran buah, dan penurunan kualitas hasil panen persik. Penyebaran bacterial spot terjadi melalui percikan air hujan, angin, atau melalui peralatan pertanian yang terkontaminasi. Untuk mengendalikan bacterial spot pada persik, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk pemilihan varietas persik yang tahan terhadap penyakit, pemangkasan yang tepat untuk meningkatkan sirkulasi udara, penyiraman yang bijaksana untuk menghindari kelembaban berlebih, dan pembersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi. Penggunaan fungisida atau antibakteri yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman persik untuk mendeteksi gejala awal bacterial spot dan penerapan tindakan pengendalian yang tepat sangat penting untuk menjaga kesehatan tanaman persik dan memaksimalkan hasil panen yang berkualitas."
  },
  {
    "name": "Peach healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Pepper bell Bacterial spot",
    "article": "Bacterial spot pada cabe bell adalah penyakit yang disebabkan oleh bakteri Xanthomonas campestris pv. vesicatoria. Penyakit ini ditandai dengan munculnya bercak-bercak berair pada daun, batang, dan buah tanaman cabe bell. Bercak tersebut dapat berkembang menjadi lesi berwarna cokelat atau hitam yang terlihat basah. Serangan penyakit ini dapat menyebabkan kerusakan pada tanaman cabe bell, termasuk kerontokan daun, pengguguran bunga, dan pembusukan buah. Penyebaran bacterial spot terjadi melalui percikan air hujan, angin, atau melalui peralatan pertanian yang terkontaminasi. Untuk mengendalikan bacterial spot pada cabe bell, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk pemilihan varietas cabe bell yang tahan terhadap penyakit, menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, dan menerapkan praktik sanitasi yang baik. Penggunaan fungisida atau antibakteri yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman cabe bell untuk mendeteksi gejala awal bacterial spot dan pengambilan tindakan pengendalian yang tepat merupakan langkah penting dalam menjaga kesehatan tanaman dan memaksimalkan hasil panen cabe bell yang berkualitas."
  },
  {
    "name": "Pepper bell healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Potato Early blight",
    "article": "Early blight pada kentang adalah penyakit yang disebabkan oleh jamur Alternaria solani. Penyakit ini ditandai dengan munculnya bercak-bercak cokelat pada daun, batang, dan buah tanaman kentang. Bercak tersebut dapat berkembang menjadi lesi berwarna cokelat dengan tepi yang jelas terlihat. Serangan penyakit ini dapat menyebabkan kerusakan pada daun, mengurangi pertumbuhan tanaman, dan mengurangi hasil panen kentang. Penyebaran early blight terjadi melalui spora jamur yang tersebar melalui percikan air hujan, angin, atau melalui peralatan pertanian yang terkontaminasi. Untuk mengendalikan early blight pada kentang, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk pemilihan varietas kentang yang tahan terhadap penyakit, pemangkasan yang tepat untuk meningkatkan sirkulasi udara, penyiraman yang bijaksana untuk menghindari kelembaban berlebih, dan pembersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman kentang untuk mendeteksi gejala awal early blight dan penerapan tindakan pengendalian yang tepat sangat penting dalam menjaga kesehatan tanaman dan memaksimalkan hasil panen kentang yang berkualitas."
  },
  {
    "name": "Potato Late blight",
    "article": "Late blight pada kentang adalah penyakit serius yang disebabkan oleh jamur Phytophthora infestans. Penyakit ini ditandai dengan munculnya bercak-bercak berwarna hijau keabu-abuan pada daun, batang, dan buah tanaman kentang. Bercak tersebut berkembang dengan cepat dan dapat berubah menjadi lesi berwarna cokelat gelap yang terlihat basah. Serangan penyakit ini dapat menyebabkan kerusakan parah pada tanaman kentang, termasuk layu dan matinya tanaman secara keseluruhan. Penyebaran late blight terjadi melalui spora jamur yang tersebar melalui udara dan air. Untuk mengendalikan late blight pada kentang, langkah-langkah pengelolaan perlu dilakukan dengan sangat hati-hati. Ini termasuk penggunaan varietas kentang yang tahan terhadap penyakit, pengendalian kelembaban dengan menghindari penyiraman berlebihan, pemangkasan yang tepat, dan pembersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi. Penggunaan fungisida yang direkomendasikan dan jadwal aplikasi yang tepat juga penting untuk mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman kentang dan tindakan pengendalian yang cepat diperlukan untuk melindungi tanaman dan menjaga hasil panen kentang yang sehat."
  },
  {
    "name": "Potato healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Raspberry healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Soybean healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Squash Powdery mildew",
    "article": "Powdery mildew pada labu adalah penyakit yang disebabkan oleh jamur Erysiphe cichoracearum atau Sphaerotheca fuliginea. Penyakit ini ditandai dengan adanya lapisan serbuk putih pada permukaan daun, batang, dan buah tanaman labu. Serangan powdery mildew dapat menyebabkan daun menguning, kering, dan akhirnya gugur. Buah labu yang terinfeksi juga dapat mengalami deformasi dan kerusakan. Penyebaran penyakit ini terjadi melalui spora jamur yang tersebar melalui angin. Untuk mengendalikan powdery mildew pada labu, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk memilih varietas labu yang tahan terhadap penyakit, memastikan sirkulasi udara yang baik dengan menjaga jarak tanam yang cukup, menghindari kelembaban berlebih dengan penyiraman yang bijaksana, dan menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman labu dan tindakan pengendalian yang cepat sangat penting untuk menjaga kesehatan tanaman dan memaksimalkan hasil panen yang berkualitas."
  },
  {
    "name": "Strawberry Leaf scorch",
    "article": "Strawberry Leaf Scorch, juga dikenal sebagai penyakit layu daun stroberi, adalah penyakit serius yang mempengaruhi tanaman stroberi. Penyakit ini disebabkan oleh bakteri Xylella fastidiosa. Gejala awal penyakit ini termasuk layu pada daun-daun stroberi, menguningnya bagian daun, dan terjadinya nekrosis pada tepi daun. Penyebaran penyakit ini terjadi melalui serangga vektor seperti kutu daun stroberi. Strawberry Leaf Scorch dapat merusak pertumbuhan dan produktivitas tanaman stroberi, menyebabkan berkurangnya hasil panen dan kualitas buah. Pengendalian penyakit ini melibatkan tindakan pencegahan seperti pemilihan bibit yang tahan, pemantauan serangga vektor, dan menjaga kebersihan kebun dengan menghilangkan tanaman yang terinfeksi. Sayangnya, belum ada pengobatan yang efektif untuk Strawberry Leaf Scorch. Oleh karena itu, upaya pencegahan dan pengelolaan penyakit ini menjadi kunci dalam menjaga keberhasilan pertanaman stroberi."
  },
  {
    "name": "Strawberry healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  },
  {
    "name": "Tomato Bacterial spot",
    "article": "Bacterial spot pada tomat adalah penyakit yang disebabkan oleh bakteri Xanthomonas vesicatoria. Penyakit ini ditandai dengan munculnya bercak-bercak basah berwarna cokelat atau hitam pada daun, batang, dan buah tanaman tomat. Bercak tersebut dapat berkembang menjadi lesi dengan pusaran warna gelap di tengahnya. Serangan penyakit ini dapat menyebabkan kerusakan pada tanaman tomat, termasuk pengeringan dan kerontokan daun, pembusukan buah, serta penurunan hasil panen. Penyebaran bacterial spot terjadi melalui percikan air hujan, angin, atau melalui peralatan pertanian yang terkontaminasi. Untuk mengendalikan bacterial spot pada tomat, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk pemilihan varietas tomat yang tahan terhadap penyakit, menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, dan menerapkan praktik sanitasi yang baik. Penggunaan fungisida atau antibakteri yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman tomat untuk mendeteksi gejala awal bacterial spot dan penerapan tindakan pengendalian yang tepat sangat penting untuk menjaga kesehatan tanaman dan memaksimalkan hasil panen yang berkualitas."
  },
  {
    "name": "Tomato Early blight",
    "article": "Early blight pada tomat adalah penyakit yang umum terjadi dan disebabkan oleh jamur Alternaria solani. Penyakit ini ditandai dengan munculnya bercak-bercak berwarna cokelat pada daun, batang, dan buah tanaman tomat. Bercak tersebut biasanya memiliki lingkaran gelap di tengahnya dan tepi yang lebih terang. Serangan early blight dapat menyebabkan kerusakan pada daun, menyebabkan pengeringan dan kerontokan, serta mempengaruhi pertumbuhan dan hasil panen tomat. Penyebaran penyakit ini terjadi melalui spora jamur yang tersebar melalui percikan air hujan, angin, atau melalui peralatan pertanian yang terkontaminasi. Untuk mengendalikan early blight pada tomat, penting untuk menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, memberikan ruang yang cukup antara tanaman, dan menyirami tanaman secara bijaksana untuk menghindari kelembaban berlebihan. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman tomat dan tindakan pengendalian yang cepat diperlukan untuk menjaga kesehatan tanaman dan memaksimalkan hasil panen yang berkualitas."
  },
  {
    "name": "Tomato Late blight",
    "article": "Late blight pada tomat adalah penyakit serius yang disebabkan oleh jamur Phytophthora infestans. Penyakit ini ditandai dengan munculnya bercak-bercak berwarna hijau keabu-abuan pada daun, batang, dan buah tanaman tomat. Bercak tersebut berkembang dengan cepat dan dapat berubah menjadi lesi berwarna cokelat gelap yang terlihat basah. Serangan penyakit ini dapat menyebabkan kerusakan parah pada tanaman tomat, termasuk layu dan matinya tanaman secara keseluruhan. Late blight menyebar dengan cepat melalui spora jamur yang tersebar melalui udara dan air. Untuk mengendalikan late blight pada tomat, penting untuk memilih varietas tomat yang tahan terhadap penyakit, menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, dan menghindari penyiraman berlebihan yang dapat menciptakan kondisi lembab. Penggunaan fungisida yang direkomendasikan dan jadwal aplikasi yang tepat juga penting dalam mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman tomat dan tindakan pengendalian yang cepat diperlukan untuk melindungi tanaman dan menjaga hasil panen tomat yang sehat."
  },
  {
    "name": "Tomato leaf mold",
    "article": "Leaf mold pada tomat adalah penyakit yang disebabkan oleh jamur Fulvia fulva, sebelumnya dikenal sebagai Cladosporium fulvum. Penyakit ini mempengaruhi daun-daun tanaman tomat dan ditandai dengan munculnya bercak-bercak kecokelatan atau kekuningan pada permukaan daun yang terinfeksi. Bercak-bercak tersebut kemudian berkembang menjadi penutup bulu-bulu jamur berwarna abu-abu atau keperakan. Serangan leaf mold dapat menyebabkan penurunan pertumbuhan tanaman, menguningnya daun, dan bahkan defoliasi. Penyebaran penyakit ini terjadi melalui spora jamur yang tersebar melalui udara. Untuk mengendalikan leaf mold pada tomat, langkah-langkah pengelolaan perlu dilakukan. Ini termasuk memberikan ruang yang cukup antara tanaman, menyirami tanaman di pagi hari untuk menghindari kelembaban berlebihan, dan menyediakan sirkulasi udara yang baik di kebun. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman tomat dan tindakan pengendalian yang cepat diperlukan untuk menjaga kesehatan tanaman dan meminimalkan kerusakan akibat leaf mold."
  },
  {
    "name": "Tomato Septoria leaf spot",
    "article": "Septoria leaf spot pada tomat adalah penyakit yang disebabkan oleh jamur Septoria lycopersici. Penyakit ini umum terjadi dan ditandai dengan munculnya bercak-bercak kecil berwarna cokelat pada daun tanaman tomat. Bercak-bercak tersebut kemudian berkembang menjadi lesi dengan pusaran berwarna cokelat gelap dan tepi yang lebih terang. Serangan penyakit ini dapat menyebabkan pengeringan dan kerontokan daun, serta merusak pertumbuhan tanaman. Penyebaran Septoria leaf spot terjadi melalui spora jamur yang tersebar melalui percikan air hujan, angin, atau melalui peralatan pertanian yang terkontaminasi. Untuk mengendalikan penyakit ini, penting untuk menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, memberikan ruang yang cukup antara tanaman, dan menyirami tanaman di pagi hari untuk menghindari kelembaban berlebihan. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini. Pemantauan rutin tanaman tomat dan tindakan pengendalian yang cepat sangat penting untuk menjaga kesehatan tanaman dan memaksimalkan hasil panen yang berkualitas."
  },
  {
    "name": "Tomato Two spotted spider mites",
    "article": "Two spotted spider mites, atau kutu laba-laba dua bintik, adalah hama yang sering menyerang tanaman tomat. Meskipun disebut kutu laba-laba, sebenarnya mereka bukanlah serangga tetapi tungau kecil. Hama ini dikenal karena menyebabkan kerusakan pada tanaman dengan mengisap cairan sel tanaman. Gejala serangan two spotted spider mites termasuk adanya bercak-bercak kuning atau kecokelatan pada daun, dan jika populasi tinggi, benang-benang tipis yang menghubungkan daun. Serangan hama ini dapat merusak pertumbuhan dan perkembangan tanaman tomat, serta mengurangi hasil panen. Untuk mengendalikan two spotted spider mites, penting untuk memantau tanaman secara teratur dan mengambil tindakan pencegahan seperti menjaga kelembapan udara yang tinggi dan menyemprotkan air pada daun untuk mengurangi populasi hama. Penggunaan insektisida nabati atau insektisida kimia tertentu juga dapat membantu mengendalikan serangan hama ini. Dengan langkah-langkah pengendalian yang tepat, serangan two spotted spider mites pada tanaman tomat dapat dikurangi dan kesehatan tanaman dapat dipertahankan."
  },
  {
    "name": "Tomato target spot",
    "article": "Target spot pada tomat adalah penyakit yang disebabkan oleh jamur Corynespora cassiicola. Penyakit ini ditandai dengan munculnya bercak-bercak berbentuk bulat atau oval berwarna cokelat pada daun tanaman tomat. Bercak-bercak tersebut memiliki pusaran berwarna gelap di tengahnya dan tepi yang lebih terang. Serangan penyakit target spot dapat menyebabkan kerusakan pada daun, mengeringnya dan kerontokan, serta berdampak negatif pada pertumbuhan dan hasil panen tanaman. Penyebaran penyakit ini terjadi melalui spora jamur yang tersebar melalui percikan air hujan, angin, atau melalui peralatan pertanian yang terkontaminasi. Untuk mengendalikan target spot pada tomat, penting untuk menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, memberikan ruang yang cukup antara tanaman, dan menyirami tanaman di pagi hari untuk menghindari kelembaban berlebihan. Penggunaan fungisida yang direkomendasikan juga dapat membantu mengendalikan penyebaran penyakit ini."
  },
  {
    "name": "Tomato Yellow leaf curl virus",
    "article": "Tomato Yellow leaf curl virus (TYLCV) adalah virus yang menyerang tanaman tomat dan menyebabkan penyakit kuning keriting pada daun. Virus ini ditularkan melalui serangga vektor, terutama kutu putih (Bemisia tabaci). Gejala infeksi TYLCV meliputi daun yang menguning, keriting, dan kerdil, serta dapat mengakibatkan penurunan hasil panen yang signifikan. Penyebaran virus ini dapat terjadi melalui serangga yang terinfeksi dan melalui benih yang terkontaminasi. Untuk mengendalikan Tomato Yellow leaf curl virus, penting untuk menerapkan tindakan pencegahan seperti penggunaan benih yang bebas virus, pengendalian serangga vektor, dan menjaga kebersihan kebun dengan menghilangkan tanaman yang terinfeksi. Selain itu, pemilihan varietas tomat yang tahan terhadap TYLCV juga dapat membantu mengurangi risiko infeksi."
  },
  {
    "name": "Tomato mosaic virus",
    "article": "Tomato mosaic virus (ToMV) adalah virus yang menyerang tanaman tomat dan menyebabkan penyakit mosaik pada daunnya. Virus ini ditularkan melalui kontak langsung antara tanaman yang terinfeksi dan yang sehat, serta melalui alat-alat pertanian yang terkontaminasi. Gejala infeksi ToMV meliputi adanya bercak-bercak kuning atau kecokelatan pada daun, kerdilnya tanaman, serta deformasi pada buah tomat. Serangan virus ini dapat menyebabkan penurunan hasil panen yang signifikan. Untuk mengendalikan Tomato mosaic virus, langkah-langkah pencegahan sangat penting, seperti menjaga kebersihan kebun dengan menghilangkan sisa-sisa tanaman yang terinfeksi, menggunakan benih yang bebas virus, serta menghindari penyebaran melalui kontak langsung dengan tanaman yang terinfeksi. Pengendalian serangga vektor yang dapat membawa virus juga diperlukan. Pemantauan rutin tanaman tomat dan tindakan pengendalian yang cepat sangat penting untuk mengurangi penyebaran virus ini dan menjaga kesehatan tanaman serta hasil panen yang baik."
  },
  {
    "name": "Tomato healthy",
    "article": "Selamat, tanaman Anda dalam kondisi yang sehat."
  }
]

export default classes
